name: foodie_hub
description: "Food delivery app connecting users with local restaurants"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_auth_web: ^5.8.13
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7  # Added for better icon support
  geolocator: ^14.0.0
  geocoding: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.3.1  # Added for splash screen customization

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#FEF6F4"  # Match your splash screen background
  adaptive_icon_foreground: "assets/logo_foreground.png"  # Optional

flutter_native_splash:
  color: "#FEF6F4"  # Match your splash screen background
  image: "assets/logo.png"
  android: true
  ios: true
  web: true
  full_screen: false

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/logo_foreground.png  # For adaptive icons
    - assets/food1.png

#  fonts:
##    - family: "Poppins"
##      fonts:
##        - asset: "assets/fonts/Poppins-Regular.ttf"
##        - asset: "assets/fonts/Poppins-Bold.ttf"
##          weight: 700