// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwn0J4sdK63RSM_Xr97QRuVEyY6d8DNF8',
    appId: '1:1084054497052:web:b73c1ddc694e791768fcd9',
    messagingSenderId: '1084054497052',
    projectId: 'foodiehub-1',
    authDomain: 'foodiehub-1.firebaseapp.com',
    storageBucket: 'foodiehub-1.firebasestorage.app',
    measurementId: 'G-4G69S0TE8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1UMT83zd45zxQBo18clKHIKN8FSIuvME',
    appId: '1:1084054497052:android:07fcc711f2bf9a4068fcd9',
    messagingSenderId: '1084054497052',
    projectId: 'foodiehub-1',
    storageBucket: 'foodiehub-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSKcv0s2zIZ5D2bBZdLBS2VmUgS-dkeOA',
    appId: '1:1084054497052:ios:e2d1f5e8c58d718e68fcd9',
    messagingSenderId: '1084054497052',
    projectId: 'foodiehub-1',
    storageBucket: 'foodiehub-1.firebasestorage.app',
    iosBundleId: 'com.foodiehub.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSKcv0s2zIZ5D2bBZdLBS2VmUgS-dkeOA',
    appId: '1:1084054497052:ios:6aeaa519b6f2607368fcd9',
    messagingSenderId: '1084054497052',
    projectId: 'foodiehub-1',
    storageBucket: 'foodiehub-1.firebasestorage.app',
    iosBundleId: 'com.aravindprojects.fuuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwn0J4sdK63RSM_Xr97QRuVEyY6d8DNF8',
    appId: '1:1084054497052:web:8ac2f8e8af41609068fcd9',
    messagingSenderId: '1084054497052',
    projectId: 'foodiehub-1',
    authDomain: 'foodiehub-1.firebaseapp.com',
    storageBucket: 'foodiehub-1.firebasestorage.app',
    measurementId: 'G-7SC6464V65',
  );
}
